# Hello d3carto

Before getting started, a few words about this package. d3carto is an R implementation of the [geoviz](https://github.com/riatelab/geoviz) JavaScript library, itself based on [d3.js](https://d3js.org/). Don't hesitate to have a look at the documentation of these libraries to understand what's under the hood. 

As you would have already understood, the aim of this package is to design maps. These maps are:

🌳 Thematic ✒️ Vectorial 👆 Interactive ♻️ Interoperable 🔎 Zoomable

Now let's see how it works.

## Installation

To install the package, just write

```R

```

Then

```R
library(d3carto)
```

Everything is now ready.

## Principles



## Syntax

There are several steps involved in creating a map. First, create the map container using the create() function. This is where you define the projection, margins, background color, etc. - in short, all the general parameters of the map. The next step is to add layers one after the other. Various functions are available for this purpose. We'll see them later. The render() function then displays the result. The various functions can be chained together with a pipe (|>)

Here is an example:

```R
create(width = 1000, projection = “EqualEarth”) |>
outline() |>
graticule() |>
base(data = aus, fill = “#CCC”, stroke = “white”)
render()
```

## 

